### PR TITLE
Make tests pass

### PR DESCRIPTION
**Pull request by TFarla**

### CODE REVIEW

**Comment by RichardLitt** [comment]
I'm not sure that we need all of those files in the `.gitignore`. All we need in there is `node_modules`. Can you pare it down?

**Comment by nicdumz** [comment]
At the same time the files in .gitignore match the current Node recommendation/boilerplate at https://github.com/github/gitignore/blob/master/Node.gitignore so I think that it makes sense.

**Comment by JaKXz** [comment]
[re: `.gitignore`](https://github.com/btford/write-good/pull/20). 👍 for passing tests though!

**Comment by RichardLitt** [comment]
Thanks!

**Pull request merged**
