### PR TITLE
Add "Other projects using write good" to README

### PR DESCRIPTION
**Pull request by Riprock**
Break out the Atom plugin to that section, and add Drafts action.

I just finished the Drafts action and wanted to ask if I could add it to the README next to the Atom plugin. I realised the Atom plugin was in a section about research, which didn't feel right so made a new section.

### CODE REVIEW

**Comment by RichardLitt** [comment]
I think that writegood mode should be added to this, too.

**Comment by Riprock** [comment]
Maybe. I had a look before and it looks like it doesn't use this javascript module so didn't move it.

**Comment by RichardLitt** [comment]
Looked closer - you're right. Keep it where it is. 

Seems like a fine edit to me.

**Comment by Riprock** [comment]
Anything needed from me?

**Comment by RichardLitt** [comment]
Nope! Pushed. :) Thanks.

**Pull request merged**
