### PR TITLE
Add remove markdown module

### PR DESCRIPTION
**Pull request by twhite96**
Not sure if this works here but I used [this library](https://github.com/stiang/remove-markdown), deleted a few lines, and added it as a module to write-good.

Not trying to reinvent the wheel or write all these RegExes from scratch. 😏

If there is anything else I could add here let me know.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks interesting to me. I want @btford to review this before merging, though. No rush on that, Brian - just seems like a nice addition.

**Comment by RichardLitt** [comment]
"No rush" might have been taken too literally. 

@twhite96 What does this add? Why should this be in this library, and not another library?

**Comment by twhite96** [comment]
Oh I forgot all about this. Idk. I am going to close this though.

**Comment by RichardLitt** [comment]
Thank you for getting back to me! Sorry about the delay.

**Pull request closed without merging**
