### PR TITLE
Frankenword

### PR DESCRIPTION
**Pull request by shakna-israel**
Added a module to detect Frankenwords.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Pretty cool. I don't know about some of them, though; for instance, `chunnel`, `chinglish`, `selfie`, `backronym`, and `conlang` all have very well established meanings, to the point where correcting someone for using them doesn't really help anyone. Selfie is in the OED, even.

**Comment by RichardLitt** [comment]
Also, you might want to squash these commits.

**Comment by duereg** [comment]
Thanks for contributing! Several things here: 

* This should be its own module 
  * [no-cliches](https://github.com/duereg/no-cliches) is an example of a module that was added after write-good was developed
* Your pull request should add your new module

**Comment by shakna-israel** [comment]
Awesome, I'll rebuild this into a module as soon as I can.

As to the inclusion of some of the words, it comes down to opinion.

I'm using Frankenword in the more modern definition of combining two words, rather than combining roots and suffixes of varying origins. Secondly, I think even well-established words like selfie, are rarely appropriate within prose.

**Comment by duereg** [comment]
@shakna-israel any progress on creating that module?

**Comment by shakna-israel** [comment]
@duereg Finally got a free day to work on this. I've rebuilt it as a package, and will be running it through it's paces today. If all works, I'll update the pull request.

**Comment by shakna-israel** [comment]
The test failures have to do with *passive voice* and *suggestions ordered by index*.

I'm not sure, because testing with Jasmine is new for me, but I don't think that has to do with my changes.

**Comment by duereg** [comment]
@shakna-israel looks like a merge conflict. write-good/write-good.js has changed for statements it detects are in the passive voice to say "may be passive voice". 

It looks like your file has the older version, which states "is passive voice".

**Comment by RichardLitt** [comment]
> As to the inclusion of some of the words, it comes down to opinion.

I would agree that it does come down to opinion. 

> I'm using Frankenword in the more modern definition of combining two words, rather than combining roots and suffixes of varying origins. Secondly, I think even well-established words like selfie, are rarely appropriate within prose.

I don't know what more modern definition you mean. This is how languages grow. I think trying to avoid 'Selfie' in prose is, if anything, far more awkward. 

I'm going to vote against this module's inclusion in the main package. @btford?

**Comment by RichardLitt** [comment]
Closing as won't fix.

**Pull request closed without merging**
